#!/bin/bash
# change the package name below 
package="com.zigzagame.evertale"
choose="halo"
while [ $choose != "0" ]
do
clear
echo "========================================================"
echo "		 Tools reroll RifkyXD"
echo "========================================================"
echo "   package name: " $package
echo "========================================================"
echo "1. Open Evertale app"
echo "2. reroll from the beginning"
echo "3. Reroll Offline story End"
echo "4. Reroll Offline story End + unlock all online story"
echo "5. Restore previous code"
echo "6. Enable mod"
echo "7. Disable mod"
echo "8. Mod status"
echo "9. Fix error draw battle"
echo "10. Save code"
echo "11. Change Package name"
echo "12. Update Tools"
echo "0. Exit"
echo "========================================================"
read -p  "choose: " choose
if [ $choose = "1" ]
then
echo "wait a moment..."
echo "opening evertale app"
am start --user 0 -n $package/com.google.firebase.MessagingUnityPlayerActivity
echo "Success"
sleep 1
elif [ $choose = "2" ]
then
echo "wait a moment..."
echo "Processing reroll"
sleep 1
rm -rf /sdcard/backup/saves_backup
cp -r /sdcard/android/data/$package/files/saves /sdcard/backup/saves_backup
rm -rf /sdcard/android/data/$package/files/saves /sdcard/android/data/$package/files/RestoreInProgress.json
mv /sdcard/android/data/$package /sdcard/android/data/com.zigzagame.evertale123
cmd package clear $package
mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$package
elif [ $choose = "3" ]
then
echo "wait a moment..."
echo "Processing Reroll offline story End" 
sleep 1
file="/data/data/com.termux/files/home/reroll10/file/rifkynormal.zip"
if [ -e $file ]
then
rm -rf /sdcard/backup/saves_backup
cp -r /sdcard/android/data/$package/files/saves /sdcard/backup/saves_backup
rm -rf /sdcard/android/data/$package/files/saves /sdcard/android/data/$package/files/RestoreInProgress.json
unzip /data/data/com.termux/files/home/reroll10/file/rifkynormal.zip -d /sdcard/android/data/$package/files/
mv /sdcard/android/data/$package /sdcard/android/data/com.zigzagame.evertale123
cmd package clear $package
mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$package
else
   echo "The file does not exist"
fi
sleep 1
elif [ $choose = "4" ]
then
echo "wait a moment..."
echo "Processing Reroll offline story End + unlock all online story"
sleep 1
file="/data/data/com.termux/files/home/reroll10/file/rifkyunlock.zip"
if [ -e $file ]
then
rm -rf /sdcard/backup/saves_backup
cp -r /sdcard/android/data/$package/files/saves /sdcard/backup/saves_backup
rm -rf /sdcard/android/data/$package/files/saves /sdcard/android/data/$package/files/RestoreInProgress.json
unzip /data/data/com.termux/files/home/reroll10/file/rifkyunlock.zip -d /sdcard/android/data/$package/files/
mv /sdcard/android/data/$package /sdcard/android/data/com.zigzagame.evertale123
cmd package clear $package
mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$package
else
   echo "The file does not exist"
fi
sleep 1
elif [ $choose = "5" ]
then
echo "wait a moment..."
echo "Restoring previous account"
rm -rf /sdcard/android/data/$package/files/saves
cp -r /sdcard/backup/saves_backup /sdcard/android/data/$package/files/saves
mv /sdcard/android/data/$package /sdcard/android/data/com.zigzagame.evertale123
cmd package clear $package
mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$package
echo "Open app and check the code"
sleep 2
elif [ $choose = "6" ]
then
echo "wait a moment..."
echo "Processing enable mod"
sleep 1
ile="/data/data/com.termux/files/home/reroll10/file/mod.zip"
if [ -e $file ]
then
   rm /sdcard/android/data/$package/files/equipment.json /sdcard/android/data/$package/files/monster.json /sdcard/android/data/$package/files/ability.json
   unzip /data/data/com.termux/files/home/reroll10/file/mod.zip -d /sdcard/android/data/$package/files/
else
   echo "The file does not exist"
fi
touch statusmod
echo "Enable" > statusmod
echo
echo "Succsess"
sleep 1
elif [ $choose = "7" ]
then
echo "wait a moment..."
echo "Processing disable Mod"
sleep 1
rm /sdcard/android/data/$package/files/equipment.json /sdcard/android/data/$package/files/monster.json /sdcard/android/data/$package/files/ability.json
touch statusmod
echo "Disable" > statusmod
echo "Succsess"
sleep 2
elif [ $choose = "8" ]
then
echo "Mod Status: "
cat statusmod
sleep 3
elif [ $choose = "9" ]
then
echo "wait a moment..."
echo "processing fix erorr"
sleep 1
cd /sdcard/android/data/$package/files
rm -rf ddsdk il2cpp unity AnimationData.json AIThreat.json Ability.json Manifest.json AbilityAI.json Monster.json AbilityAISequence.json MonsterConditions.json AbilityComponent.json MonsterRanker.json AbilityConfig.json Package.json AbilityEffect.json QuestReward.json AttackScalor.json BattleBehavior.json BattleConditions.json Shops.json Boss.json TargetingData.json Buff.json BundleReqs.json ClientConfig.json Clusters.json ValidShards.json Equipment.json Weapon.json GCodes.json LocalBundleHashes.json LocalNotifications.json
cd -
echo "Succees"
touch statusmod
echo "Disable" > statusmod
sleep 1
elif [ $choose = "10" ]
then
echo "Save code"
sleep 1
files="/sdcard/savecode"
echo
read -p "Server:" server
read -p "Code:" kode
echo "Server : " $server >> $files
echo "Code : " $kode >> $files
echo "======================" >> $files
echo "Succees"
sleep 1
elif [ $choose = "11" ]
then
echo "wait a moment..."
echo "Change package name"
sleep 1
nano /data/data/com.termux/files/usr/bin/reroll
touch statusmod
echo "Unknow" > statusmod
echo "Jalankan Tool Kembali untuk menjalankan perubahan"
sleep 2
exit
elif [ $choose = "12" ]
then
echo "Check for updates"
cd /data/data/com.termux/files/home/reroll10
git pull
read -p "update y/n: " ok
	if [ $ok = "y" ]
	then
	./install
	echo "update done, restart tool"
	exit
	elif [ $ok = "t" ]
	then
	echo "canceled "
	else
	echo "option not available"
	echo "Update canceled"
	fi
sleep 3
cd -
elif [ $choose = "0" ]
then
echo "exit"
else 
echo "option not available"
sleep 2
fi
done
