#!/bin/bash
pilih=9
while [ $pilih -ne 0 ]
do
clear
echo "======================="
echo "Tool reroll by Rifky"
echo "======================="
echo "1. Open Evertale app"
echo "2. Reroll"
echo "3. Reroll Offline story tamat"
echo "4. Reroll offline story tamat + unlock all online story"
echo "5. Aktifkan Mod"
echo "6. Nonaktifkan Mod"
echo "7. Status Mod"
echo "0. Exit"
read -p  "pilih nomor: " pilih
if [ $pilih -eq 1 ]
then
echo "Proses membuka  evertale"
am start --user 0 -n com.zigzagame.evertale/com.google.firebase.MessagingUnityPlayerActivity
echo "Success"
sleep 1
elif [ $pilih -eq 2 ]
then
echo "Proses Reroll"
sleep 1
sudo rm -rf /sdcard/android/data/com.zigzagame.evertale/files/saves /sdcard/android/data/com.zigzagame.evertale/files/RestoreInProgress.json
sudo mv /sdcard/android/data/com.zigzagame.evertale /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear com.zigzagame.evertale
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/com.zigzagame.evertale
sleep 2
elif [ $pilih -eq 3 ]
then
echo "Proses Reroll offline story tamat" 
sleep 1
file="/data/data/com.termux/files/usr/file/rifkynormal.zip"
if [ -e $file ]
then
sudo rm -rf /sdcard/android/data/com.zigzagame.evertale/files/saves /sdcard/android/data/com.zigzagame.evertale/files/RestoreInProgress.json
sudo unzip /data/data/com.termux/files/usr/file/rifkynormal.zip -d /sdcard/android/data/com.zigzagame.evertale/files/
sudo mv /sdcard/android/data/com.zigzagame.evertale /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear com.zigzagame.evertale
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/com.zigzagame.evertale
else
   echo "The file does not exist"
fi
sleep 2
elif [ $pilih -eq 4 ]
then
echo "Proses Reroll offline story tamat + unlock all online story"
sleep 1
file="/data/data/com.termux/files/usr/file/rifkyunlock.zip"
if [ -e $file ]
then
sudo rm -rf /sdcard/android/data/com.zigzagame.evertale/files/saves /sdcard/android/data/com.zigzagame.evertale/files/RestoreInProgress.json
sudo unzip /data/data/com.termux/files/usr/file/rifkyunlock.zip -d /sdcard/android/data/com.zigzagame.evertale/files/
sudo mv /sdcard/android/data/com.zigzagame.evertale /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear com.zigzagame.evertale
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/com.zigzagame.evertale
else
   echo "The file does not exist"
fi
sleep 2
elif [ $pilih -eq 5 ]
then
echo "Proses Mengaktifkan Mod"
sleep 1
ile="/data/data/com.termux/files/usr/file/mod.zip"
if [ -e $file ]
then
   sudo rm /sdcard/android/data/com.zigzagame.evertale/files/equipment.json /sdcard/android/data/com.zigzagame.evertale/files/monster.json /sdcard/android/data/com.zigzagame.evertale/files/ability.json
   sudo unzip /data/data/com.termux/files/usr/file/mod.zip -d /sdcard/android/data/com.zigzagame.evertale/files/
else
   echo "The file does not exist"
fi
touch statusmod
echo "Aktif" > statusmod
echo
echo "Succsess"
sleep 2
elif [ $pilih -eq 6 ]
then
echo "Proses Nonaktifkan Mod"
sleep 1
file="/data/data/com.termux/files/usr/file/unmod.zip"
if [ -e $file ]
then
sudo rm /sdcard/android/data/com.zigzagame.evertale/files/equipment.json /sdcard/android/data/com.zigzagame.evertale/files/monster.json /sdcard/android/data/com.zigzagame.evertale/files/ability.json
sudo unzip /data/data/com.termux/files/usr/file/unmod.zip -d /sdcard/android/data/com.zigzagame.evertale/files/
else
   echo "The file does not exist"
fi
touch statusmod
echo "Nonaktif" > statusmod
echo "Succsess"
sleep 2
elif [ $pilih -eq 7 ]
then
echo "Status Mod"
cat statusmod
sleep 4
elif [ $pilih -eq 0 ]
then
echo "exit"
else 
echo "pilihan tidak ada"
fi
done
