#!/bin/bash
#UBAH PACKAGE NAME DIBAWAH
paket="com.zigzagame.evertale"
pilih=1
while [ $pilih -ne 0 ]
do
clear
echo "==========================="
echo "Tool reroll by Rifky v1.8"
echo "==========================="
echo "package name: " $paket
echo "==========================="
echo "1. Open Evertale app"
echo "2. Reroll"
echo "3. Reroll Offline story tamat"
echo "4. Reroll offline story tamat + unlock all online story"
echo "5. Pulihkan kode sebelumnya"
echo "6. Aktifkan Mod"
echo "7. Nonaktifkan Mod"
echo "8. Status Mod"
echo "9. Fix error draw"
echo "10. Simpan Kode"
echo "11. Ubah Package name"
echo "12. Update Tool"
echo "0. Exit"
read -p  "pilih nomor: " pilih
if [ $pilih -eq 1 ]
then
echo "Proses membuka  evertale"
am start --user 0 -n $paket/com.google.firebase.MessagingUnityPlayerActivity
echo "Success"
sleep 1
elif [ $pilih -eq 2 ]
then
echo "Proses Reroll"
sleep 1
sudo rm -rf /sdcard/android/data/$paket/files/saves_backup
sudo cp -r /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/saves_backup
sudo rm -rf /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/RestoreInProgress.json
sudo mv /sdcard/android/data/$paket /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear $paket
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$paket
sleep 1
elif [ $pilih -eq 3 ]
then
echo "Proses Reroll offline story tamat" 
sleep 1
file="/data/data/com.termux/files/usr/file/rifkynormal.zip"
if [ -e $file ]
then
sudo rm -rf /sdcard/android/data/$paket/files/saves_backup
sudo cp -r /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/saves_backup
sudo rm -rf /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/RestoreInProgress.json
sudo unzip /data/data/com.termux/files/usr/file/rifkynormal.zip -d /sdcard/android/data/$paket/files/
sudo mv /sdcard/android/data/$paket /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear $paket
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$paket
else
   echo "The file does not exist"
fi
sleep 1
elif [ $pilih -eq 4 ]
then
echo "Proses Reroll offline story tamat + unlock all online story"
sleep 1
file="/data/data/com.termux/files/usr/file/rifkyunlock.zip"
if [ -e $file ]
then
sudo rm -rf /sdcard/android/data/$paket/files/saves_backup
sudo cp -r /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/saves_backup
sudo rm -rf /sdcard/android/data/$paket/files/saves /sdcard/android/data/$paket/files/RestoreInProgress.json
sudo unzip /data/data/com.termux/files/usr/file/rifkyunlock.zip -d /sdcard/android/data/$paket/files/
sudo mv /sdcard/android/data/$paket /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear $paket
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$paket
else
   echo "The file does not exist"
fi
sleep 1
elif [ $pilih -eq 5 ]
then
echo "Proses memulihkan kode"
sudo rm -rf /sdcard/android/data/$paket/files/saves
sudo cp -r /sdcard/android/data/$paket/files/saves_backup /sdcard/android/data/$paket/files/saves
sudo mv /sdcard/android/data/$paket /sdcard/android/data/com.zigzagame.evertale123
sudo cmd package clear $paket
sudo mv /sdcard/android/data/com.zigzagame.evertale123 /sdcard/android/data/$paket
echo "Buka evertale untuk mengecek kode"
sleep 2
elif [ $pilih -eq 6 ]
then
echo "Proses Mengaktifkan Mod"
sleep 1
ile="/data/data/com.termux/files/usr/file/mod.zip"
if [ -e $file ]
then
   sudo rm /sdcard/android/data/$paket/files/equipment.json /sdcard/android/data/$paket/files/monster.json /sdcard/android/data/$paket/files/ability.json
   sudo unzip /data/data/com.termux/files/usr/file/mod.zip -d /sdcard/android/data/$paket/files/
else
   echo "The file does not exist"
fi
touch statusmod
echo "Aktif" > statusmod
echo
echo "Succsess"
sleep 1
elif [ $pilih -eq 7 ]
then
echo "Proses Nonaktifkan Mod"
sleep 1
file="/data/data/com.termux/files/usr/file/unmod.zip"
if [ -e $file ]
then
sudo rm /sdcard/android/data/$paket/files/equipment.json /sdcard/android/data/$paket/files/monster.json /sdcard/android/data/$paket/files/ability.json
sudo unzip /data/data/com.termux/files/usr/file/unmod.zip -d /sdcard/android/data/$paket/files/
else
   echo "The file does not exist"
fi
touch statusmod
echo "Nonaktif" > statusmod
echo "Succsess"
sleep 2
elif [ $pilih -eq 8 ]
then
echo "Status Mod: "
cat statusmod
sleep 3
elif [ $pilih -eq 9 ]
then
echo "proses perbaikan erorr"
sleep 1
cd /sdcard/android/data/$paket/files
sudo rm -rf ddsdk il2cpp unity AnimationData.json AIThreat.json Ability.json Manifest.json AbilityAI.json Monster.json AbilityAISequence.json MonsterConditions.json AbilityComponent.json MonsterRanker.json AbilityConfig.json Package.json AbilityEffect.json QuestReward.json AttackScalor.json BattleBehavior.json BattleConditions.json Shops.json Boss.json TargetingData.json Buff.json BundleReqs.json ClientConfig.json Clusters.json ValidShards.json Equipment.json Weapon.json GCodes.json LocalBundleHashes.json LocalNotifications.json
cd -
echo "Succees"
touch statusmod
echo "Nonaktif" > statusmod
sleep 1
elif [ $pilih -eq 10 ]
then
echo "Simpan Kode"
sleep 1
files="/sdcard/simpanankode"
echo
read -p "Nama:" nama
read -p "Server:" server
read -p "Kode:" kode
echo "Nama : " $nama  >>  $files
echo "Server : " $server >> $files
echo "Kode : " $kode >> $files
echo "======================" >> $files
echo "Succees"
sleep 1
elif [ $pilih -eq 11 ]
then
echo "ubah"
sleep 1
nano /data/data/com.termux/files/usr/bin/reroll
touch statusmod
echo "Unknow" > statusmod
echo "Jalankan Tool Kembali untuk menjalankan perubahan"
sleep 2
exit
elif [ $pilih -eq 12 ]
then
echo "Memeriksa update"
cd /data/data/com.termux/files/home/reroll
git pull
read -p "update y/n:" ok
	if [ $ok = "y" ]
	then
	./install
	echo "update selesai mulai ulang program"
	exit
	elif [ $ok = "t" ]
	then
	echo "Dibatalkan"
	else
	echo "pilihan tidak ada"
	echo "Update dibatalkan"
	fi
sleep 3
cd -
elif [ $pilih -eq 0 ]
then
echo "exit"
else 
echo "pilihan tidak ada"
fi
done
