#!/bin/bash
rm /data/data/com.termux/files/usr/bin/reroll10 /data/data/com.termux/files/usr/bin/statusmod
rm -rf /data/data/com.termux/files/usr/file/reroll10
rm reroll10
cd file
rm mod.zip rifkynormal.zip rifkyunlock.zip
echo "success"
